import { Application } from "express";
import companyRoutes from "./companyRoutes.js";
import clientRoutes from "./clientRoutes.js";
import bookingRoutes from "./bookingRoutes.js";
import truckRoutes from "./truckRoutes.js";
import driverRoutes from "./driverRoutes.js";
import assignmentRoutes from "./assignmentRoutes.js";
import settlementRoutes from "./settlementRoutes.js";
import truckInspectionRoutes from "./truckInspectionRoutes.js";
import liveTrackingRoutes from "./liveTrackingRoutes.js";
import travelSummaryRoutes from "./travelSummaryRoutes.js";
import tollRoutes from "./tollRoutes.js";
import goodsTypeRoutes from "./goodsTypeRoutes.js";
import uploadRoutes from "./uploadRoutes.js";
import chatRoutes from "./chatRoutes.js";
import routeRoutes from "./routeRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import mileageRoutes from "./mileageRoutes.js";
import ledgerRoutes from "./ledgerRoutes.js";

export function registerRoutes(app: Application): void {
  app.use("/api/companies", companyRoutes);
  app.use("/api/clients", clientRoutes);
  app.use("/api/bookings", bookingRoutes);
  app.use("/api/trucks", truckRoutes);
  app.use("/api/drivers", driverRoutes);
  app.use("/api/assignments", assignmentRoutes);
  app.use("/api/settlements", settlementRoutes);
  app.use("/api/truck-inspections", truckInspectionRoutes);
  app.use("/api/livetrack", liveTrackingRoutes);
  app.use("/api/travel-summary", travelSummaryRoutes);
  app.use("/api/toll", tollRoutes);
  app.use("/api/goods-types", goodsTypeRoutes);
  app.use("/api/upload", uploadRoutes);
  app.use("/api/chat", chatRoutes);
  app.use("/api/routes", routeRoutes);
  app.use("/api/notifications", notificationRoutes);
  app.use("/api/mileage", mileageRoutes);
  app.use("/api/ledger", ledgerRoutes);
}
